const COMMAND_API_VERSION = 1 as const
const SOURCE_SPACE_SIZE = 100
const DEFAULT_COLOR = '#000000'
const CIRCLE_SEGMENTS = 32
const DEFAULT_BEZIER_SEGMENTS = 24
const ELLIPSE_SEGMENTS = 48
const DEFAULT_ARC_SEGMENTS = 24
const MIN_FILL_SCANLINE_WIDTH = 0.2
const MAX_FILL_STROKES = 512

export {
  CIRCLE_SEGMENTS,
  COMMAND_API_VERSION,
  DEFAULT_ARC_SEGMENTS,
  DEFAULT_BEZIER_SEGMENTS,
  DEFAULT_COLOR,
  ELLIPSE_SEGMENTS,
  MAX_FILL_STROKES,
  MIN_FILL_SCANLINE_WIDTH,
  SOURCE_SPACE_SIZE,
}
